import{test}from '@playwright/test' 

test('E-2-E testing in Playwright',async({page})=>{
await page.goto("https://www.saucedemo.com/")
const username =page.locator('#user-name')
await username.fill('standard_user')
const password = page.locator('#password')
await password.fill('secret_sauce')
const loginbutton = page.locator('#login-button')
await loginbutton.click()
const OnesieAddCart = page.locator('#add-to-cart-sauce-labs-onesie')
await OnesieAddCart.click()
const CartButton = page.locator('#shopping_cart_container')
await CartButton.click()
const Checkout = page.locator('#checkout')
await Checkout.click()
const CheckoutName = page.locator('#first-name')
await CheckoutName.fill('Nandu')
const CheckoutSurname = page.locator('#last-name')
await CheckoutSurname.fill('Nair')
const CheckoutZip = page.locator('#postal-code')
await CheckoutZip.fill('60001')
const CheckoutContinue = page.locator('#continue')
await CheckoutContinue.click()
const CheckoutFinish = page.locator('#finish')
await CheckoutFinish.click()
const CheckoutBackHome = page.locator('#back-to-products')
await CheckoutBackHome.click()

})